### ISSUE TITLE
Rev trigger seems to be missing?

### ISSUE THREAD

**Issue by SGArmstrang** [HeadshotKinetics/GryphonSLX#1]
Files seem to be missing the rev trigger.

**Comment by HeadshotKinetics** [comment]
Fixed, should be there now.

**Comment by SGArmstrang** [comment]
Thank you,

I have a potentially bigger ask, can you do a 42.5mm cage for an HVZ load
out? 40mm crush is going to be too spicy.

Thank you,

Jay
